# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7368ddd66092509d0e69eabffbc23408cc4d83b4fffb9947f71befe8954147cb3f6d4ddac186c614ab8ba169aee34af580b8eafce0064e473bae6c8008bcd078

test:
  secret_key_base: d8d5f45bbef26126f0025afe994f3ae1261f6ce0315ed60a5095b5a17a438c453aa85ea3d986855c77386d3697eba1c5411e1ee27e8f156327f819ab7dfba49d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
